// Teo Kai Xiang, A0272558U
// Test cases generated by GPT-5.3-Codex via planning mode. Reviewed and edited by me afterwards

import React from "react";
import { render, screen, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom/extend-expect";
import axios from "axios";
import useCategory from "./useCategory";
import { mockAxiosByUrl } from "../mocks/mockAxios";

const CATEGORY_URL = "/api/v1/category/get-category";
const CATEGORIES = [
  { _id: "c1", name: "Electronics", slug: "electronics" },
  { _id: "c2", name: "Books", slug: "books" },
];

const HookConsumer = () => {
  const categories = useCategory();
  const isArray = Array.isArray(categories);

  return (
    <div>
      <div data-testid="is-array">{String(isArray)}</div>
      <div data-testid="category-count">{isArray ? categories.length : -1}</div>
      {isArray &&
        categories.map((category) => (
          <div key={category._id} data-testid="category-name">
            {category.name}
          </div>
        ))}
    </div>
  );
};

jest.mock("axios");

describe("useCategory Hook", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe("Happy Path Tests - when everything works as expected, the hook", () => {
    it("fetches categories on mount and returns category list", async () => {
      // ------------ Arrange ------------
      mockAxiosByUrl(axios.get, {
        [CATEGORY_URL]: {
          data: { success: true, category: CATEGORIES },
        },
      });

      // ------------ Act ------------
      render(<HookConsumer />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(screen.getByTestId("category-count")).toHaveTextContent("2");
      });
      expect(screen.getByText("Electronics")).toBeInTheDocument();
      expect(screen.getByText("Books")).toBeInTheDocument();
      expect(axios.get).toHaveBeenCalledWith(CATEGORY_URL);
    });

    it("handles empty category array successfully", async () => {
      // ------------ Arrange ------------
      mockAxiosByUrl(axios.get, {
        [CATEGORY_URL]: {
          data: { success: true, category: [] },
        },
      });

      // ------------ Act ------------
      render(<HookConsumer />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(screen.getByTestId("category-count")).toHaveTextContent("0");
      });
      expect(screen.queryAllByTestId("category-name")).toHaveLength(0);
      expect(screen.getByTestId("is-array")).toHaveTextContent("true");
    });
  });

  describe("Unhappy Path Tests - when something breaks, the hook", () => {
    it("handles API rejection gracefully and preserves empty array state", async () => {
      // ------------ Arrange ------------
      axios.get.mockRejectedValueOnce(new Error("Request failed"));

      // ------------ Act ------------
      render(<HookConsumer />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(axios.get).toHaveBeenCalledWith(CATEGORY_URL);
      });
      expect(screen.getByTestId("category-count")).toHaveTextContent("0");
      expect(screen.getByTestId("is-array")).toHaveTextContent("true");
    });

    it("handles malformed payload with missing category field without throwing", async () => {
      // ------------ Arrange ------------
      mockAxiosByUrl(axios.get, {
        [CATEGORY_URL]: {
          data: {},
        },
      });

      // ------------ Act ------------
      render(<HookConsumer />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(axios.get).toHaveBeenCalledWith(CATEGORY_URL);
      });
      expect(screen.getByTestId("is-array")).toBeInTheDocument();
      expect(screen.getByTestId("category-count")).toBeInTheDocument();
      expect(screen.queryAllByTestId("category-name")).toHaveLength(0);
    });
  });
});
