//
// Mervyn Teo Zi Yan, A0273039A
//
// Integration tests for Authentication components: Routes + Controllers + Middlewares + Models.
// Tests go through the full HTTP stack using supertest to ensure end-to-end reliability:
//   route → requireSignIn → isAdmin → authController → userModel (real MongoDB)
//
// This verifies:
//   - Auth middlewares correctly block unauthenticated, invalid, or unauthorized requests.
//   - The database correctly enforces role-based access (isAdmin checks real DB records).
//   - Full integration: The JWT generated by `loginController` is perfectly compatible
//     with the validation logic in `requireSignIn`.
//   - Edge cases: Handles scenarios like a user being deleted after receiving a valid JWT.

import mongoose from "mongoose";
import request from "supertest";
import express from "express";
import jwt from "jsonwebtoken";
import { MongoMemoryServer } from "mongodb-memory-server";

import userModel from "../../../../models/userModel.js";
import {
    testController,
    registerController,
    loginController
} from "../../../../controllers/authController.js";
import { requireSignIn, isAdmin } from "../../../../middlewares/authMiddleware.js";

// Use a fixed test secret so auth middleware and token signing agree
process.env.JWT_SECRET = "test-jwt-secret-integration";

// Silence console noise in tests
beforeAll(() => {
    jest.spyOn(console, "error").mockImplementation(() => {});
    jest.spyOn(console, "warn").mockImplementation(() => {});
});

beforeEach(() => jest.spyOn(console, "log").mockImplementation(() => {}));

let mongod;
let app;

beforeAll(async () => {
    mongod = await MongoMemoryServer.create();
    await mongoose.connect(mongod.getUri());

    // Setup Express App and wire up the controllers/middlewares
    const authRoutes = express.Router();
    authRoutes.post("/register", registerController);
    authRoutes.post("/login", loginController);
    authRoutes.get("/test", requireSignIn, isAdmin, testController);

    app = express();
    app.use(express.json());
    app.use("/api/v1/auth", authRoutes);
});

afterAll(async () => {
    await mongoose.connection.dropDatabase();
    await mongoose.connection.close();
    await mongod.stop();
});

afterEach(async () => {
    jest.restoreAllMocks();
    await userModel.deleteMany({});
});

// ─── Middleware Edge Cases ───────────────────────────────────────────────

describe("Auth Middleware — Protected Routes & Role Validation", () => {
    test("GET /test returns 401 with no Authorization header", async () => {
        const res = await request(app).get("/api/v1/auth/test");
        expect(res.status).toBe(401);
        expect(res.body.message).toBe("Invalid or expired token");
    });

    test("GET /test returns 401 with an invalidly formatted token", async () => {
        const res = await request(app)
            .get("/api/v1/auth/test")
            .set("Authorization", "not-a-valid-jwt");
        expect(res.status).toBe(401);
    });

    test("GET /test returns 401 when a valid token is provided, but user is not admin (role 0)", async () => {
        const user = await userModel.create({
            name: "Regular User", email: "regular@test.com", password: "pass123",
            phone: "99999999", address: "1 User Street", answer: "test", role: 0,
        });
        const token = jwt.sign({ _id: user._id }, process.env.JWT_SECRET, { expiresIn: "1h" });

        const res = await request(app)
            .get("/api/v1/auth/test")
            .set("Authorization", token);

        expect(res.status).toBe(401);
        expect(res.body.message).toBe("UnAuthorized Access");
    });

    test("GET /test returns 401 when a valid admin token is used, but the user was deleted from DB", async () => {
        // This tests the `if (!user)` branch inside your `isAdmin` middleware
        const fakeId = new mongoose.Types.ObjectId();
        const token = jwt.sign({ _id: fakeId }, process.env.JWT_SECRET, { expiresIn: "1h" });

        const res = await request(app)
            .get("/api/v1/auth/test")
            .set("Authorization", token);

        expect(res.status).toBe(401);
        expect(res.body.message).toBe("UnAuthorized Access");
    });

    test("GET /test returns 200 when a valid admin token is provided", async () => {
        const adminUser = await userModel.create({
            name: "Admin User", email: "admin@test.com", password: "pass123",
            phone: "88888888", address: "1 Admin Street", answer: "test", role: 1,
        });
        const token = jwt.sign({ _id: adminUser._id }, process.env.JWT_SECRET, { expiresIn: "1h" });

        const res = await request(app)
            .get("/api/v1/auth/test")
            .set("Authorization", token);

        expect(res.status).toBe(200);
        expect(res.text).toBe("Protected Routes");
    });
});

// ─── Full Auth Flow Integration ──────────────────────────────────────────

describe("Full Auth Lifecycle via HTTP — Register → Login → Access Protected Route", () => {
    test("Successfully completes the auth cycle utilizing real controllers and middleware", async () => {
        const credentials = {
            name: "Integration Admin",
            email: "flow@test.com",
            password: "SecurePass1!",
            phone: "12345678",
            address: "1 Flow Street",
            answer: "flow answer"
        };

        // Step 1: Register the user via HTTP
        const registerRes = await request(app)
            .post("/api/v1/auth/register")
            .send(credentials);
        expect(registerRes.status).toBe(201);

        // Elevate user to admin directly in DB for test purposes
        await userModel.findOneAndUpdate({ email: credentials.email }, { role: 1 });

        // Step 2: Login via HTTP to get the dynamically generated token
        const loginRes = await request(app)
            .post("/api/v1/auth/login")
            .send({ email: credentials.email, password: credentials.password });
        expect(loginRes.status).toBe(200);
        expect(loginRes.body.token).toBeDefined();

        const activeToken = loginRes.body.token;

        // Step 3: Use the dynamically generated token to access the protected route
        const protectedRes = await request(app)
            .get("/api/v1/auth/test")
            .set("Authorization", activeToken);

        expect(protectedRes.status).toBe(200);
        expect(protectedRes.text).toBe("Protected Routes");
    });
});
