// Teo Kai Xiang, A0272558U
// Test cases generated by GPT-5.3-Codex via planning mode. Reviewed and edited by me afterwards

import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom/extend-expect";
import axios from "axios";
import toast from "react-hot-toast";
import CartPage from "./CartPage";
import { mockAxiosByUrl, mockAxiosByUrlWithError } from "../mocks/mockAxios";

const TOKEN_URL = "/api/v1/product/braintree/token";

const PRODUCT_ONE = {
  _id: "p1",
  name: "Laptop",
  description: "A powerful laptop for development and testing workflows",
  price: 1000,
};

const PRODUCT_TWO = {
  _id: "p2",
  name: "Mouse",
  description: "An ergonomic mouse for daily productivity",
  price: 50,
};

const mockNavigate = jest.fn();
const mockSetAuth = jest.fn();
const mockSetCart = jest.fn();

let mockAuthValue;
let mockCartValue;
let mockDropInInstance;
let mockDropInShouldSetInstance;

jest.mock("axios");

jest.mock("react-hot-toast", () => ({
  success: jest.fn(),
}));

jest.mock("react-router-dom", () => ({
  ...jest.requireActual("react-router-dom"),
  useNavigate: () => mockNavigate,
}));

jest.mock("./../components/Layout", () => ({ children }) => (
  <div data-testid="layout">{children}</div>
));

jest.mock("../context/auth", () => ({
  useAuth: () => [mockAuthValue, mockSetAuth],
}));

jest.mock("../context/cart", () => ({
  useCart: () => [mockCartValue, mockSetCart],
}));

jest.mock("braintree-web-drop-in-react", () => {
  const React = require("react");
  return ({ onInstance }) => {
    React.useEffect(() => {
      if (mockDropInShouldSetInstance) {
        onInstance(mockDropInInstance);
      }
    }, [onInstance]);
    return <div data-testid="dropin">DropIn</div>;
  };
});

describe("CartPage Component", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockAuthValue = { user: null, token: "" };
    mockCartValue = [];
    mockDropInInstance = {
      requestPaymentMethod: jest.fn().mockResolvedValue({ nonce: "nonce-123" }),
    };
    mockDropInShouldSetInstance = true;

    jest.spyOn(Storage.prototype, "setItem").mockImplementation(jest.fn());
    jest.spyOn(Storage.prototype, "removeItem").mockImplementation(jest.fn());
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe("Happy Path Tests - when everything works as expected, the component", () => {
    it("renders guest greeting and cart count message for unauthenticated users", async () => {
      // Summary: Verifies guest users see the correct greeting, cart count, and checkout prompt.
      // Flow: mock guest auth, seeded cart, and token response -> render component -> assert guest heading, item count, and login prompt.
      // ------------ Arrange ------------
      mockAuthValue = { user: null, token: "" };
      mockCartValue = [PRODUCT_ONE, PRODUCT_TWO];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-1" } },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(screen.getByText("Hello Guest")).toBeInTheDocument();
      });
      expect(
        screen.getByText(/You Have 2 items in your cart/i),
      ).toBeInTheDocument();
      expect(screen.getByText(/please login to checkout/i)).toBeInTheDocument();
    });

    it("renders authenticated user greeting and cart summary message", async () => {
      // Summary: Verifies authenticated users see personalized greeting text and cart summary without the guest prompt.
      // Flow: mock authed user with address, seeded cart, and token response -> render component -> assert user greeting and item count.
      // ------------ Arrange ------------
      mockAuthValue = {
        token: "auth-token",
        user: { name: "John Doe", address: "123 Main St" },
      };
      mockCartValue = [PRODUCT_ONE];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-2" } },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(screen.getByText(/Hello\s+John Doe/)).toBeInTheDocument();
      });
      expect(
        screen.getByText(/You Have 1 items in your cart/i),
      ).toBeInTheDocument();
      expect(
        screen.queryByText(/please login to checkout/i),
      ).not.toBeInTheDocument();
    });

    it("renders cart items with expected item details", async () => {
      // Summary: Verifies cart item cards render the expected name, truncated description, and price label.
      // Flow: mock guest auth, one cart item, and token response -> render component -> assert item fields are visible.
      // ------------ Arrange ------------
      mockAuthValue = { user: null, token: "" };
      mockCartValue = [PRODUCT_ONE];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-3" } },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(screen.getByText(PRODUCT_ONE.name)).toBeInTheDocument();
      });
      expect(
        screen.getByText(PRODUCT_ONE.description.substring(0, 30)),
      ).toBeInTheDocument();
      expect(
        screen.getByText(`Price : ${PRODUCT_ONE.price}`),
      ).toBeInTheDocument();
    });

    it("removes an item when Remove is clicked and syncs cart to localStorage", async () => {
      // Summary: Verifies removing a cart item updates both context state and persisted localStorage state.
      // Flow: mock cart with two items -> render component -> click first Remove button -> assert setCart call and localStorage update.
      // ------------ Arrange ------------
      mockAuthValue = { user: null, token: "" };
      mockCartValue = [PRODUCT_ONE, PRODUCT_TWO];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-4" } },
      });

      // ------------ Act ------------
      render(<CartPage />);
      const removeButtons = await screen.findAllByRole("button", {
        name: "Remove",
      });
      fireEvent.click(removeButtons[0]);

      // ------------ Assert ------------
      expect(mockSetCart).toHaveBeenCalledWith([PRODUCT_TWO]);
      expect(localStorage.setItem).toHaveBeenCalledWith(
        "cart",
        JSON.stringify([PRODUCT_TWO]),
      );
    });

    it("shows total price in USD format", async () => {
      // Summary: Verifies the total price is formatted using the expected USD currency display.
      // Flow: mock cart with two priced items -> render component -> assert formatted total text is shown.
      // ------------ Arrange ------------
      mockAuthValue = { user: null, token: "" };
      mockCartValue = [PRODUCT_ONE, PRODUCT_TWO];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-5" } },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(screen.getByText("Total : $1,050.00")).toBeInTheDocument();
      });
    });

    it("renders DropIn and enables Make Payment when user has token, cart and address", async () => {
      // Summary: Verifies checkout becomes actionable only when the user is authenticated and has an address plus cart items.
      // Flow: mock authed user with address, one cart item, and token response -> render component -> assert DropIn renders and Make Payment is enabled.
      // ------------ Arrange ------------
      mockAuthValue = {
        token: "auth-token",
        user: { name: "John Doe", address: "123 Main St" },
      };
      mockCartValue = [PRODUCT_ONE];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-6" } },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      expect(await screen.findByTestId("dropin")).toBeInTheDocument();
      await waitFor(() => {
        const makePaymentButton = screen.getByRole("button", {
          name: "Make Payment",
        });
        expect(makePaymentButton).toBeEnabled();
      });
    });

    it("shows Update Address button for authenticated user without address and navigates to profile", async () => {
      // Summary: Verifies users missing an address are redirected toward profile completion instead of payment.
      // Flow: mock authed user without address -> render component -> click Update Address -> assert profile navigation call.
      // ------------ Arrange ------------
      mockAuthValue = {
        token: "auth-token",
        user: { name: "John Doe", address: "" },
      };
      mockCartValue = [PRODUCT_ONE];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-7" } },
      });

      // ------------ Act ------------
      render(<CartPage />);
      const updateAddressButton = await screen.findByRole("button", {
        name: "Update Address",
      });
      fireEvent.click(updateAddressButton);

      // ------------ Assert ------------
      expect(mockNavigate).toHaveBeenCalledWith("/dashboard/user/profile");
    });
  });

  describe("Unhappy Path Tests - when something breaks, the component", () => {
    it("shows login prompt for checkout when user is unauthenticated", async () => {
      // Summary: Verifies checkout attempts by guests route them to the login page with cart return state.
      // Flow: mock guest auth and seeded cart -> render component -> click login-to-checkout button -> assert navigate call with /cart state.
      // ------------ Arrange ------------
      mockAuthValue = { user: null, token: "" };
      mockCartValue = [PRODUCT_ONE];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-8" } },
      });

      // ------------ Act ------------
      render(<CartPage />);
      const loginButton = await screen.findByRole("button", {
        name: "Plase Login to checkout",
      });
      fireEvent.click(loginButton);

      // ------------ Assert ------------
      expect(mockNavigate).toHaveBeenCalledWith("/login", {
        state: "/cart",
      });
    });

    it("handles token API failure gracefully without crashing", async () => {
      // Summary: Verifies token-fetch failure leaves the page usable and hides payment UI.
      // Flow: mock guest auth, seeded cart, and token API error -> render component -> assert Cart Summary remains visible and DropIn is absent.
      // ------------ Arrange ------------
      mockAuthValue = { user: null, token: "" };
      mockCartValue = [PRODUCT_ONE];
      mockAxiosByUrlWithError(axios.get, {
        [TOKEN_URL]: {
          response: {
            status: 500,
            data: { success: false, message: "token error" },
          },
          message: "Request failed with status code 500",
        },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(screen.getByText("Cart Summary")).toBeInTheDocument();
      });
      expect(screen.queryByTestId("dropin")).not.toBeInTheDocument();
    });

    it("resets loading state when requesting payment method fails", async () => {
      // Summary: Verifies a DropIn payment-method error resets button state and avoids posting payment.
      // Flow: mock authed user with address, cart item, token response, and failing requestPaymentMethod -> render component -> click Make Payment -> assert button re-enables and no POST occurs.
      // ------------ Arrange ------------
      mockAuthValue = {
        token: "auth-token",
        user: { name: "John Doe", address: "123 Main St" },
      };
      mockCartValue = [PRODUCT_ONE];
      mockDropInInstance = {
        requestPaymentMethod: jest
          .fn()
          .mockRejectedValue(new Error("Payment method error")),
      };
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-9" } },
      });

      // ------------ Act ------------
      render(<CartPage />);
      const makePaymentButton = await screen.findByRole("button", {
        name: "Make Payment",
      });
      fireEvent.click(makePaymentButton);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: "Make Payment" }),
        ).toBeEnabled();
      });
      expect(axios.post).not.toHaveBeenCalled();
      expect(toast.success).not.toHaveBeenCalled();
    });

    it("does not render DropIn or Make Payment when user has no address", async () => {
      // Summary: Verifies checkout widgets are hidden when the authenticated user has not supplied an address.
      // Flow: mock authed user without address and token response -> render component -> assert Update Address appears while DropIn and Make Payment stay hidden.
      // ------------ Arrange ------------
      mockAuthValue = {
        token: "auth-token",
        user: { name: "John Doe", address: "" },
      };
      mockCartValue = [PRODUCT_ONE];
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-10" } },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: "Update Address" }),
        ).toBeInTheDocument();
      });
      expect(screen.queryByTestId("dropin")).not.toBeInTheDocument();
      expect(
        screen.queryByRole("button", { name: "Make Payment" }),
      ).not.toBeInTheDocument();
    });

    it("disables Make Payment button when DropIn instance is unavailable", async () => {
      // Summary: Verifies checkout remains blocked when the DropIn instance never initializes.
      // Flow: mock authed user with address, cart item, token response, and no DropIn instance callback -> render component -> assert Make Payment is disabled.
      // ------------ Arrange ------------
      mockAuthValue = {
        token: "auth-token",
        user: { name: "John Doe", address: "123 Main St" },
      };
      mockCartValue = [PRODUCT_ONE];
      mockDropInShouldSetInstance = false;
      mockAxiosByUrl(axios.get, {
        [TOKEN_URL]: { data: { clientToken: "client-token-11" } },
      });

      // ------------ Act ------------
      render(<CartPage />);

      // ------------ Assert ------------
      const makePaymentButton = await screen.findByRole("button", {
        name: "Make Payment",
      });
      expect(makePaymentButton).toBeDisabled();
    });
  });
});
