// Teo Kai Xiang, A0272558U
// Test cases generated by GPT-5.3-Codex via planning mode. Reviewed and edited by me afterwards

import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import "@testing-library/jest-dom/extend-expect";
import Categories from "./Categories";
import useCategory from "../hooks/useCategory";

const CATEGORIES = [
  { _id: "c1", name: "Electronics", slug: "electronics" },
  { _id: "c2", name: "Books", slug: "books" },
];

jest.mock("../hooks/useCategory", () => jest.fn());

jest.mock("./../components/Layout", () => ({ children }) => (
  <div data-testid="layout">{children}</div>
));

describe("Categories Component", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe("Happy Path Tests - when everything works as expected, the component", () => {
    it("renders one category link button per category from the hook", () => {
      // ------------ Arrange ------------
      useCategory.mockReturnValue(CATEGORIES);

      // ------------ Act ------------
      render(
        <MemoryRouter>
          <Categories />
        </MemoryRouter>,
      );

      // ------------ Assert ------------
      const links = screen.getAllByRole("link");
      expect(links).toHaveLength(CATEGORIES.length);
      expect(screen.getByText("Electronics")).toBeInTheDocument();
      expect(screen.getByText("Books")).toBeInTheDocument();
    });

    it("renders correct route targets for each category link", () => {
      // ------------ Arrange ------------
      useCategory.mockReturnValue(CATEGORIES);

      // ------------ Act ------------
      render(
        <MemoryRouter>
          <Categories />
        </MemoryRouter>,
      );

      // ------------ Assert ------------
      expect(screen.getByRole("link", { name: "Electronics" })).toHaveAttribute(
        "href",
        "/category/electronics",
      );
      expect(screen.getByRole("link", { name: "Books" })).toHaveAttribute(
        "href",
        "/category/books",
      );
    });

    it("renders layout wrapper and category section structure", () => {
      // ------------ Arrange ------------
      useCategory.mockReturnValue([CATEGORIES[0]]);

      // ------------ Act ------------
      render(
        <MemoryRouter>
          <Categories />
        </MemoryRouter>,
      );

      // ------------ Assert ------------
      expect(screen.getByTestId("layout")).toBeInTheDocument();
      expect(
        screen.getByRole("link", { name: "Electronics" }),
      ).toBeInTheDocument();
    });
  });

  describe("Unhappy Path Tests - when something breaks, the component", () => {
    it("renders safely when hook returns an empty category list", () => {
      // ------------ Arrange ------------
      useCategory.mockReturnValue([]);

      // ------------ Act ------------
      render(
        <MemoryRouter>
          <Categories />
        </MemoryRouter>,
      );

      // ------------ Assert ------------
      expect(screen.getByTestId("layout")).toBeInTheDocument();
      expect(screen.queryAllByRole("link")).toHaveLength(0);
    });

    it("renders safely when category fields are partially missing", () => {
      // ------------ Arrange ------------
      useCategory.mockReturnValue([{ _id: "c3", name: "Unnamed Slugless" }]);

      // ------------ Act ------------
      render(
        <MemoryRouter>
          <Categories />
        </MemoryRouter>,
      );

      // ------------ Assert ------------
      const link = screen.getByRole("link", { name: "Unnamed Slugless" });
      expect(link).toBeInTheDocument();
      expect(link).toHaveAttribute("href", "/category/undefined");
    });
  });
});
