// Teo Kai Xiang, A0272558U
// Test cases generated by GPT-5.3-Codex via planning mode. Reviewed and edited by me afterwards

import React from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import "@testing-library/jest-dom/extend-expect";
import { CartProvider, useCart } from "./cart";

const TestCartConsumer = () => {
  const [cart, setCart] = useCart();

  return (
    <div>
      <div data-testid="cart-count">{cart.length}</div>
      <button
        onClick={() =>
          setCart([
            ...cart,
            { _id: "p-new", name: "New Item", description: "new", price: 1 },
          ])
        }
      >
        Add Item
      </button>
    </div>
  );
};

describe("CartContext and CartProvider", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe("Happy Path Tests - when everything works as expected, the context", () => {
    it("hydrates cart state from localStorage on mount", () => {
      // ------------ Arrange ------------
      const storedCart = JSON.stringify([
        { _id: "p1", name: "Stored Product", description: "desc", price: 10 },
      ]);
      jest.spyOn(Storage.prototype, "getItem").mockReturnValue(storedCart);

      // ------------ Act ------------
      render(
        <CartProvider>
          <TestCartConsumer />
        </CartProvider>,
      );

      // ------------ Assert ------------
      expect(screen.getByTestId("cart-count")).toHaveTextContent("1");
      expect(localStorage.getItem).toHaveBeenCalledWith("cart");
    });

    it("updates cart state through useCart setter in consumers", () => {
      // ------------ Arrange ------------
      jest.spyOn(Storage.prototype, "getItem").mockReturnValue(null);

      // ------------ Act ------------
      render(
        <CartProvider>
          <TestCartConsumer />
        </CartProvider>,
      );
      fireEvent.click(screen.getByRole("button", { name: "Add Item" }));

      // ------------ Assert ------------
      expect(screen.getByTestId("cart-count")).toHaveTextContent("1");
    });
  });

  describe("Unhappy Path Tests - when something breaks, the context", () => {
    it("keeps default empty cart when localStorage has no cart key", () => {
      // ------------ Arrange ------------
      jest.spyOn(Storage.prototype, "getItem").mockReturnValue(null);

      // ------------ Act ------------
      render(
        <CartProvider>
          <TestCartConsumer />
        </CartProvider>,
      );

      // ------------ Assert ------------
      expect(screen.getByTestId("cart-count")).toHaveTextContent("0");
      expect(localStorage.getItem).toHaveBeenCalledWith("cart");
    });

    it("throws when localStorage cart value is invalid JSON", () => {
      // ------------ Arrange ------------
      jest.spyOn(Storage.prototype, "getItem").mockReturnValue("invalid-json");

      // ------------ Act & Assert ------------
      expect(() =>
        render(
          <CartProvider>
            <TestCartConsumer />
          </CartProvider>,
        ),
      ).not.toThrow(); // The component should handle the error and not throw
    });
  });
});
