// A0272558U, Teo Kai Xiang
// Generated by GPT 5.4 based on test plans written by me. Reviewed after generation.

import { test, expect } from "@playwright/test";
import mongoose from "mongoose";
import dotenv from "dotenv";
import categoryModel from "../../../models/categoryModel.js";
import productModel from "../../../models/productModel.js";

dotenv.config();

test.use({ storageState: { cookies: [], origins: [] } });
test.afterAll(async () => {
  if (mongoose.connection.readyState !== 0) {
    await mongoose.disconnect();
  }
});

const getCategoryOptions = (page) =>
  page.locator(".filters .ant-checkbox-wrapper");

const getPriceOptions = (page) => page.locator(".filters .ant-radio-wrapper");

const getFilterPanel = (page) => page.locator(".home-page .filters");

const getProductPanel = (page) => page.locator(".home-page .col-md-9");

const getHomeProductCards = (page) =>
  page.locator(
    ".home-page .col-md-9 .card:has(button:has-text('ADD TO CART'))",
  );

const getHomeProductCardByName = (page, productName) =>
  getHomeProductCards(page).filter({
    has: page.locator(".card-title", { hasText: productName }),
  });

const getLoadMoreButton = (page) =>
  page.getByRole("button", { name: /loadmore/i });

const getCartBadge = (page) => page.locator("sup.ant-badge-count");

const buildFutureDate = (order) =>
  new Date(Date.now() + 1000 * 60 * 60 * 24 * 365 * 50 + order * 1000);

const buildSeededProduct = ({
  name,
  price,
  categoryId,
  slugPrefix,
  order,
}) => ({
  name,
  slug: `${slugPrefix}-${order}`,
  description: `${name} description for homepage pagination coverage.`,
  price,
  category: categoryId,
  quantity: 10,
  shipping: true,
  createdAt: buildFutureDate(order),
  updatedAt: buildFutureDate(order),
});

const seededPriceRange = [20, 39];

const waitForFilterResponse = (page) =>
  page.waitForResponse(
    (response) =>
      response.url().includes("/api/v1/product/product-filters") &&
      response.request().method() === "POST",
  );

const waitForProductListResponse = (page, pageNumber) =>
  page.waitForResponse(
    (response) =>
      response.url().includes(`/api/v1/product/product-list/${pageNumber}`) &&
      response.request().method() === "GET",
  );

const loadHomePage = async (page) => {
  await page.goto("/");
  await expect(page.locator("h1.text-center")).toContainText("All Products");
  await expect(getCategoryOptions(page).first()).toBeVisible({
    timeout: 10000,
  });
  await expect(getPriceOptions(page).first()).toBeVisible({ timeout: 10000 });
  await expect(page.locator("a[href='/cart']")).toBeVisible();
  await expect(getHomeProductCards(page).first()).toBeVisible({
    timeout: 10000,
  });
};

const parseCurrency = (priceText) => Number(priceText.replace(/[^0-9.]/g, ""));

const formatCurrency = (amount) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);

const getProductSnapshot = async (card) => {
  const productName =
    (await card.locator(".card-title").first().textContent())?.trim() || "";
  const priceText =
    (await card.locator(".card-price").textContent())?.trim() || "";

  return {
    name: productName,
    priceText,
    price: parseCurrency(priceText),
  };
};

const ensureMongoConnection = async () => {
  if (mongoose.connection.readyState === 1) {
    return;
  }

  if (mongoose.connection.readyState === 2) {
    await mongoose.connection.asPromise();
    return;
  }

  await mongoose.connect(process.env.MONGO_URL);
};

const seedLoadMoreData = async () => {
  await ensureMongoConnection();

  const uniqueTag = `pw-home-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const category = await categoryModel.create({
    name: `Playwright Loadmore ${uniqueTag}`,
    slug: `playwright-loadmore-${uniqueTag}`,
  });

  const productsToCreate = [
    buildSeededProduct({
      name: "Aurora Keyboard",
      price: 25,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 1,
    }),
    buildSeededProduct({
      name: "Nimbus Mouse",
      price: 32,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 2,
    }),
    buildSeededProduct({
      name: "Atlas Headset",
      price: 28,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 3,
    }),
    buildSeededProduct({
      name: "Orbit Stand",
      price: 29,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 4,
    }),
    buildSeededProduct({
      name: "Comet Webcam",
      price: 31,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 5,
    }),
    buildSeededProduct({
      name: "Pulse Dock",
      price: 34,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 6,
    }),
    buildSeededProduct({
      name: "Nova Charger",
      price: 27,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 7,
    }),
    buildSeededProduct({
      name: "Echo Cable",
      price: 22,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 8,
    }),
  ];

  const insertedProducts = await productModel.create(productsToCreate);
  const sortedProducts = [...insertedProducts].sort(
    (first, second) => second.createdAt.getTime() - first.createdAt.getTime(),
  );

  return {
    category,
    products: sortedProducts,
  };
};

const cleanupSeededLoadMoreData = async ({ categoryId, productIds }) => {
  await ensureMongoConnection();
  await productModel.deleteMany({ _id: { $in: productIds } });
  await categoryModel.deleteOne({ _id: categoryId });
};

const seedFilterScenarioData = async () => {
  await ensureMongoConnection();

  const uniqueTag = `pw-home-filter-${Date.now()}-${Math.random()
    .toString(36)
    .slice(2, 8)}`;
  const targetCategory = await categoryModel.create({
    name: `Playwright Electronics ${uniqueTag}`,
    slug: `playwright-electronics-${uniqueTag}`,
  });
  const secondaryCategory = await categoryModel.create({
    name: `Playwright Books ${uniqueTag}`,
    slug: `playwright-books-${uniqueTag}`,
  });

  const insertedProducts = await productModel.create([
    buildSeededProduct({
      name: `Signal Keyboard ${uniqueTag}`,
      price: 25,
      categoryId: targetCategory._id,
      slugPrefix: `${uniqueTag}-signal`,
      order: 1,
    }),
    buildSeededProduct({
      name: `Vector Mouse ${uniqueTag}`,
      price: 39,
      categoryId: targetCategory._id,
      slugPrefix: `${uniqueTag}-vector`,
      order: 2,
    }),
    buildSeededProduct({
      name: `Atlas Monitor ${uniqueTag}`,
      price: 55,
      categoryId: targetCategory._id,
      slugPrefix: `${uniqueTag}-atlas`,
      order: 3,
    }),
    buildSeededProduct({
      name: `Paper Trail ${uniqueTag}`,
      price: 30,
      categoryId: secondaryCategory._id,
      slugPrefix: `${uniqueTag}-paper`,
      order: 4,
    }),
  ]);

  const productsByName = Object.fromEntries(
    insertedProducts.map((product) => [product.name, product]),
  );
  const targetCategoryProducts = [
    productsByName[`Signal Keyboard ${uniqueTag}`],
    productsByName[`Vector Mouse ${uniqueTag}`],
    productsByName[`Atlas Monitor ${uniqueTag}`],
  ];
  const priceRangeProducts = [
    productsByName[`Signal Keyboard ${uniqueTag}`],
    productsByName[`Vector Mouse ${uniqueTag}`],
    productsByName[`Paper Trail ${uniqueTag}`],
  ];
  const combinedFilterProducts = [
    productsByName[`Signal Keyboard ${uniqueTag}`],
    productsByName[`Vector Mouse ${uniqueTag}`],
  ];

  return {
    targetCategory,
    secondaryCategory,
    targetCategoryProducts,
    priceRangeProducts,
    combinedFilterProducts,
    outOfRangeProduct: productsByName[`Atlas Monitor ${uniqueTag}`],
    crossCategoryProduct: productsByName[`Paper Trail ${uniqueTag}`],
    allProducts: insertedProducts,
  };
};

const cleanupSeededFilterData = async ({ categoryIds, productIds }) => {
  await ensureMongoConnection();
  await productModel.deleteMany({ _id: { $in: productIds } });
  await categoryModel.deleteMany({ _id: { $in: categoryIds } });
};

test.describe("Functional E2E", () => {
  test("applies category and price filters to show matching products", async ({
    page,
  }) => {
    test.slow();

    const seededData = await seedFilterScenarioData();

    try {
      await loadHomePage(page);

      const categoryResponsePromise = waitForFilterResponse(page);
      await getCategoryOptions(page)
        .getByText(seededData.targetCategory.name)
        .click();
      const categoryResponse = await categoryResponsePromise;
      expect(categoryResponse.ok()).toBeTruthy();

      const priceResponsePromise = waitForFilterResponse(page);
      await getPriceOptions(page).getByText("$20 to 39").click();
      const priceResponse = await priceResponsePromise;
      expect(priceResponse.ok()).toBeTruthy();

      const productCards = getHomeProductCards(page);
      await expect(productCards).toHaveCount(
        seededData.combinedFilterProducts.length,
        {
          timeout: 10000,
        },
      );

      for (const product of seededData.combinedFilterProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }

      await expect(getProductPanel(page)).not.toContainText(
        seededData.outOfRangeProduct.name,
      );
      await expect(getProductPanel(page)).not.toContainText(
        seededData.crossCategoryProduct.name,
      );
    } finally {
      await cleanupSeededFilterData({
        categoryIds: [
          seededData.targetCategory._id,
          seededData.secondaryCategory._id,
        ],
        productIds: seededData.allProducts.map((product) => product._id),
      });
    }
  });

  test("adds filtered products to cart and shows them in the cart summary", async ({
    page,
  }) => {
    test.slow();

    const seededData = await seedFilterScenarioData();

    try {
      await loadHomePage(page);

      const categoryResponsePromise = waitForFilterResponse(page);
      await getCategoryOptions(page)
        .getByText(seededData.targetCategory.name)
        .click();
      const categoryResponse = await categoryResponsePromise;
      expect(categoryResponse.ok()).toBeTruthy();

      const priceResponsePromise = waitForFilterResponse(page);
      await getPriceOptions(page).getByText("$20 to 39").click();
      const priceResponse = await priceResponsePromise;
      expect(priceResponse.ok()).toBeTruthy();

      const productCards = getHomeProductCards(page);
      await expect(productCards).toHaveCount(
        seededData.combinedFilterProducts.length,
        {
          timeout: 10000,
        },
      );

      const addedProducts = [];
      let expectedTotal = 0;

      for (let index = 0; index < seededData.combinedFilterProducts.length; index += 1) {
        const card = productCards.nth(index);
        const product = await getProductSnapshot(card);

        addedProducts.push(product.name);
        expectedTotal += product.price;

        await card.getByRole("button", { name: "ADD TO CART" }).click();
        await expect(getCartBadge(page)).toHaveAttribute(
          "title",
          String(index + 1),
        );
      }

      await page.locator("a[href='/cart']").click();
      await expect(page).toHaveURL("/cart");

      for (const productName of addedProducts) {
        await expect(page.locator(".cart-page")).toContainText(productName);
      }

      await expect(page.locator(".cart-summary")).toContainText("Total :");
      await expect(page.locator(".cart-summary h4")).toContainText(
        formatCurrency(expectedTotal),
      );
    } finally {
      await cleanupSeededFilterData({
        categoryIds: [
          seededData.targetCategory._id,
          seededData.secondaryCategory._id,
        ],
        productIds: seededData.allProducts.map((product) => product._id),
      });
    }
  });

  test("RESET FILTERS restores the unfiltered seeded products after category and price filters are applied", async ({
    page,
  }) => {
    test.slow();

    const seededData = await seedFilterScenarioData();

    try {
      await loadHomePage(page);

      const categoryResponsePromise = waitForFilterResponse(page);
      await getCategoryOptions(page)
        .getByText(seededData.targetCategory.name)
        .click();
      const categoryResponse = await categoryResponsePromise;
      expect(categoryResponse.ok()).toBeTruthy();

      const priceResponsePromise = waitForFilterResponse(page);
      await getPriceOptions(page).getByText("$20 to 39").click();
      const priceResponse = await priceResponsePromise;
      expect(priceResponse.ok()).toBeTruthy();

      await expect(getProductPanel(page)).not.toContainText(
        seededData.outOfRangeProduct.name,
      );

      await Promise.all([
        page.waitForLoadState("domcontentloaded"),
        getFilterPanel(page).getByRole("button", { name: /reset filters/i }).click(),
      ]);

      await expect(
        page.getByRole("checkbox", { name: seededData.targetCategory.name }),
      ).not.toBeChecked();
      await expect(page.getByRole("radio", { name: "$20 to 39" })).not.toBeChecked();

      for (const product of seededData.allProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }
    } finally {
      await cleanupSeededFilterData({
        categoryIds: [
          seededData.targetCategory._id,
          seededData.secondaryCategory._id,
        ],
        productIds: seededData.allProducts.map((product) => product._id),
      });
    }
  });

  test("More Details opens the seeded product details page from the homepage", async ({
    page,
  }) => {
    test.slow();

    const seededData = await seedFilterScenarioData();
    const targetProduct = seededData.combinedFilterProducts[0];

    try {
      await loadHomePage(page);

      const targetCard = getHomeProductCardByName(page, targetProduct.name);
      await expect(targetCard).toHaveCount(1, { timeout: 10000 });
      await targetCard.getByRole("button", { name: "More Details" }).click();

      await expect(page).toHaveURL(new RegExp(`/product/${targetProduct.slug}$`));
      await expect(
        page.getByRole("heading", { name: /product details/i }),
      ).toBeVisible();
      await expect(page.locator(".product-details-info")).toContainText(
        targetProduct.name,
      );
      await expect(page.locator(".product-details-info")).toContainText(
        seededData.targetCategory.name,
      );
    } finally {
      await cleanupSeededFilterData({
        categoryIds: [
          seededData.targetCategory._id,
          seededData.secondaryCategory._id,
        ],
        productIds: seededData.allProducts.map((product) => product._id),
      });
    }
  });

  test("Load more appends the next page of unfiltered products", async ({
    page,
  }) => {
    test.slow();

    const seededData = await seedLoadMoreData();

    try {
      await loadHomePage(page);

      const productCards = getHomeProductCards(page);
      const expectedInitialProducts = seededData.products.slice(0, 6);
      const expectedPageTwoProducts = seededData.products.slice(6);

      await expect(productCards).toHaveCount(expectedInitialProducts.length, {
        timeout: 10000,
      });

      for (const product of expectedInitialProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }

      await expect(getLoadMoreButton(page)).toBeVisible();

      const loadMoreResponsePromise = waitForProductListResponse(page, 2);
      await getLoadMoreButton(page).click();
      const loadMoreResponse = await loadMoreResponsePromise;
      expect(loadMoreResponse.ok()).toBeTruthy();

      const responseData = await loadMoreResponse.json();
      const appendedProducts = responseData?.products || [];

      expect(appendedProducts.length).toBeGreaterThanOrEqual(
        expectedPageTwoProducts.length,
      );

      await expect(productCards).toHaveCount(
        expectedInitialProducts.length + appendedProducts.length,
        {
          timeout: 10000,
        },
      );

      for (const product of expectedPageTwoProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }
    } finally {
      await cleanupSeededLoadMoreData({
        categoryId: seededData.category._id,
        productIds: seededData.products.map((product) => product._id),
      });
    }
  });

  test("Load more adheres to the category and price filters while loading more filtered products", async ({
    page,
  }) => {
    test.slow();

    const seededData = await seedLoadMoreData();

    try {
      await loadHomePage(page);

      const expectedFilteredPageOneProducts = seededData.products.slice(0, 6);
      const expectedFilteredPageTwoProducts = seededData.products.slice(6);

      const categoryResponsePromise = waitForFilterResponse(page);
      await getCategoryOptions(page)
        .getByText(seededData.category.name)
        .click();
      const categoryResponse = await categoryResponsePromise;
      expect(categoryResponse.ok()).toBeTruthy();

      const priceResponsePromise = waitForFilterResponse(page);
      await getPriceOptions(page).getByText("$20 to 39").click();
      const priceResponse = await priceResponsePromise;
      expect(priceResponse.ok()).toBeTruthy();

      const productCards = getHomeProductCards(page);
      await expect(productCards).toHaveCount(
        expectedFilteredPageOneProducts.length,
        {
          timeout: 10000,
        },
      );

      await expect(getLoadMoreButton(page)).toBeVisible();

      const loadMoreResponsePromise = waitForFilterResponse(page);
      await getLoadMoreButton(page).click();
      const loadMoreResponse = await loadMoreResponsePromise;
      expect(loadMoreResponse.ok()).toBeTruthy();

      const requestPayload = loadMoreResponse.request().postDataJSON();
      expect(requestPayload?.page).toBe(2);
      expect(requestPayload?.checked || []).toEqual([
        seededData.category._id.toString(),
      ]);
      expect(requestPayload?.radio || []).toEqual(seededPriceRange);

      const responseData = await loadMoreResponse.json();
      const appendedProducts = responseData?.products || [];

      expect(appendedProducts.length).toBe(
        expectedFilteredPageTwoProducts.length,
      );

      await expect(productCards).toHaveCount(
        expectedFilteredPageOneProducts.length + appendedProducts.length,
        { timeout: 10000 },
      );

      for (const product of expectedFilteredPageOneProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }

      for (const product of expectedFilteredPageTwoProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }
    } finally {
      await cleanupSeededLoadMoreData({
        categoryId: seededData.category._id,
        productIds: seededData.products.map((product) => product._id),
      });
    }
  });
});

test.describe("User interface", () => {
  test("shows the banner, product heading, and filter section headings", async ({
    page,
  }) => {
    await loadHomePage(page);

    await expect(page.getByAltText("bannerimage")).toBeVisible();
    await expect(page.locator("h1.text-center")).toContainText("All Products");
    await expect(
      getFilterPanel(page).getByText("Filter By Category"),
    ).toBeVisible();
    await expect(
      getFilterPanel(page).getByText("Filter By Price"),
    ).toBeVisible();
    await expect(
      getFilterPanel(page).getByRole("button", { name: /reset filters/i }),
    ).toBeVisible();
  });

  test("shows category checkboxes and price radio options", async ({
    page,
  }) => {
    await loadHomePage(page);

    await expect(getCategoryOptions(page).first()).toBeVisible();
    await expect(getPriceOptions(page).first()).toBeVisible();
    expect(await getCategoryOptions(page).count()).toBeGreaterThan(0);
    expect(await getPriceOptions(page).count()).toBeGreaterThan(0);
  });

  test("shows product cards with image, name, price, description, and action buttons", async ({
    page,
  }) => {
    await loadHomePage(page);

    const firstCard = getHomeProductCards(page).first();
    await expect(firstCard).toBeVisible();
    await expect(firstCard.locator("img.card-img-top")).toBeVisible();
    await expect(firstCard.locator(".card-title").first()).toBeVisible();
    await expect(firstCard.locator(".card-price")).toContainText("$");
    await expect(firstCard.locator(".card-text")).toBeVisible();
    await expect(
      firstCard.getByRole("button", { name: "More Details" }),
    ).toBeVisible();
    await expect(
      firstCard.getByRole("button", { name: "ADD TO CART" }),
    ).toBeVisible();
  });

  test("shows the header cart link and cart badge on the homepage", async ({
    page,
  }) => {
    await loadHomePage(page);

    await expect(page.locator("a[href='/cart']")).toBeVisible();
    await expect(getCartBadge(page)).toBeVisible();
    await expect(getCartBadge(page)).toHaveAttribute("title", "0");
  });
});
