// A0272558U, Teo Kai Xiang
// Generated by GPT 5.4 based on test plans written by me. Reviewed after generation.

import { test, expect } from "@playwright/test";
import mongoose from "mongoose";
import dotenv from "dotenv";
import categoryModel from "../../../models/categoryModel.js";
import productModel from "../../../models/productModel.js";

dotenv.config();

test.use({ storageState: { cookies: [], origins: [] } });
test.afterAll(async () => {
  if (mongoose.connection.readyState !== 0) {
    await mongoose.disconnect();
  }
});

const getCategoryOptions = (page) =>
  page.locator(".filters .ant-checkbox-wrapper");

const getPriceOptions = (page) => page.locator(".filters .ant-radio-wrapper");

const getFilterPanel = (page) => page.locator(".home-page .filters");

const getProductPanel = (page) => page.locator(".home-page .col-md-9");

const getHomeProductCards = (page) =>
  page.locator(
    ".home-page .col-md-9 .card:has(button:has-text('ADD TO CART'))",
  );

const getLoadMoreButton = (page) =>
  page.getByRole("button", { name: /loadmore/i });

const getCartBadge = (page) => page.locator("sup.ant-badge-count");

const buildSeededProduct = ({ name, price, categoryId, slugPrefix, order }) => ({
  name,
  slug: `${slugPrefix}-${order}`,
  description: `${name} description for homepage pagination coverage.`,
  price,
  category: categoryId,
  quantity: 10,
  shipping: true,
  createdAt: new Date(Date.now() + order * 1000),
  updatedAt: new Date(Date.now() + order * 1000),
});

const seededPriceRange = [20, 39];

const waitForFilterResponse = (page) =>
  page.waitForResponse(
    (response) =>
      response.url().includes("/api/v1/product/product-filters") &&
      response.request().method() === "POST",
  );

const waitForProductListResponse = (page, pageNumber) =>
  page.waitForResponse(
    (response) =>
      response.url().includes(`/api/v1/product/product-list/${pageNumber}`) &&
      response.request().method() === "GET",
  );

const loadHomePage = async (page) => {
  await page.goto("/");
  await expect(page.locator("h1.text-center")).toContainText("All Products");
  await expect(getCategoryOptions(page).first()).toBeVisible({
    timeout: 10000,
  });
  await expect(getPriceOptions(page).first()).toBeVisible({ timeout: 10000 });
  await expect(page.locator("a[href='/cart']")).toBeVisible();
  await expect(getHomeProductCards(page).first()).toBeVisible({
    timeout: 10000,
  });
};

const parseCurrency = (priceText) => Number(priceText.replace(/[^0-9.]/g, ""));

const formatCurrency = (amount) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);

const getProductSnapshot = async (card) => {
  const productName =
    (await card.locator(".card-title").first().textContent())?.trim() || "";
  const priceText =
    (await card.locator(".card-price").textContent())?.trim() || "";

  return {
    name: productName,
    priceText,
    price: parseCurrency(priceText),
  };
};

const ensureMongoConnection = async () => {
  if (mongoose.connection.readyState === 0) {
    await mongoose.connect(process.env.MONGO_URL);
  }
};

const seedLoadMoreData = async () => {
  await ensureMongoConnection();

  const uniqueTag = `pw-home-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const category = await categoryModel.create({
    name: `Playwright Loadmore ${uniqueTag}`,
    slug: `playwright-loadmore-${uniqueTag}`,
  });

  const productsToCreate = [
    buildSeededProduct({
      name: "Aurora Keyboard",
      price: 25,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 1,
    }),
    buildSeededProduct({
      name: "Nimbus Mouse",
      price: 32,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 2,
    }),
    buildSeededProduct({
      name: "Atlas Headset",
      price: 28,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 3,
    }),
    buildSeededProduct({
      name: "Orbit Stand",
      price: 29,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 4,
    }),
    buildSeededProduct({
      name: "Comet Webcam",
      price: 31,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 5,
    }),
    buildSeededProduct({
      name: "Pulse Dock",
      price: 34,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 6,
    }),
    buildSeededProduct({
      name: "Nova Charger",
      price: 27,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 7,
    }),
    buildSeededProduct({
      name: "Echo Cable",
      price: 22,
      categoryId: category._id,
      slugPrefix: uniqueTag,
      order: 8,
    }),
  ];

  const insertedProducts = await productModel.create(productsToCreate);
  const sortedProducts = [...insertedProducts].sort(
    (first, second) => second.createdAt.getTime() - first.createdAt.getTime(),
  );

  return {
    category,
    products: sortedProducts,
  };
};

const cleanupSeededLoadMoreData = async ({ categoryId, productIds }) => {
  await ensureMongoConnection();
  await productModel.deleteMany({ _id: { $in: productIds } });
  await categoryModel.deleteOne({ _id: categoryId });
};

const findWorkingFilterCombination = async (
  page,
  { requireLoadMore = false } = {},
) => {
  await loadHomePage(page);

  const categoryCount = await getCategoryOptions(page).count();
  const priceCount = await getPriceOptions(page).count();

  if (categoryCount === 0 || priceCount === 0) {
    return null;
  }

  for (
    let categoryIndex = 0;
    categoryIndex < categoryCount;
    categoryIndex += 1
  ) {
    await loadHomePage(page);

    const categoryOptions = getCategoryOptions(page);
    const priceOptions = getPriceOptions(page);

    const categoryLabel =
      (await categoryOptions.nth(categoryIndex).textContent())?.trim() || "";

    const categoryResponsePromise = waitForFilterResponse(page);
    await categoryOptions.nth(categoryIndex).click();
    const categoryResponse = await categoryResponsePromise;
    expect(categoryResponse.ok()).toBeTruthy();

    for (let priceIndex = 0; priceIndex < priceCount; priceIndex += 1) {
      const priceLabel =
        (await priceOptions.nth(priceIndex).textContent())?.trim() || "";

      const priceResponsePromise = waitForFilterResponse(page);
      await priceOptions.nth(priceIndex).click();
      const priceResponse = await priceResponsePromise;
      expect(priceResponse.ok()).toBeTruthy();

      const responseData = await priceResponse.json();
      const products = responseData?.products || [];
      const total = responseData?.total ?? products.length;

      if (
        products.length > 0 &&
        (!requireLoadMore || total > products.length)
      ) {
        const requestPayload = priceResponse.request().postDataJSON();
        return {
          categoryLabel,
          priceLabel,
          checked: requestPayload?.checked || [],
          radio: requestPayload?.radio || [],
          products,
          total,
        };
      }
    }
  }

  return null;
};

test.describe("Functional E2E", () => {
  test("applies category and price filters to show matching products", async ({
    page,
  }) => {
    test.slow();

    const filterCombination = await findWorkingFilterCombination(page);
    if (!filterCombination) {
      return test.skip();
    }

    const productCards = getHomeProductCards(page);
    await expect(productCards).toHaveCount(filterCombination.products.length, {
      timeout: 10000,
    });

    for (const product of filterCombination.products) {
      await expect(page.locator(".home-page .col-md-9")).toContainText(
        product.name,
      );
    }

    await expect(getLoadMoreButton(page)).toHaveCount(
      filterCombination.total > filterCombination.products.length ? 1 : 0,
    );
  });

  test("adds filtered products to cart and shows them in the cart summary", async ({
    page,
  }) => {
    test.slow();

    const filterCombination = await findWorkingFilterCombination(page);
    if (!filterCombination) {
      return test.skip();
    }

    const productCards = getHomeProductCards(page);
    await expect(productCards).toHaveCount(filterCombination.products.length, {
      timeout: 10000,
    });

    const addCount = Math.min(await productCards.count(), 2);
    if (addCount === 0) {
      return test.skip();
    }

    const addedProducts = [];
    let expectedTotal = 0;

    for (let index = 0; index < addCount; index += 1) {
      const card = productCards.nth(index);
      const product = await getProductSnapshot(card);

      addedProducts.push(product.name);
      expectedTotal += product.price;

      await card.getByRole("button", { name: "ADD TO CART" }).click();
      await expect(getCartBadge(page)).toHaveAttribute(
        "title",
        String(index + 1),
      );
    }

    await page.locator("a[href='/cart']").click();
    await expect(page).toHaveURL("/cart");

    for (const productName of addedProducts) {
      await expect(page.locator(".cart-page")).toContainText(productName);
    }

    await expect(page.locator(".cart-summary")).toContainText("Total :");
    await expect(page.locator(".cart-summary h4")).toContainText(
      formatCurrency(expectedTotal),
    );
  });

  test("appends the next page of unfiltered products", async ({ page }) => {
    test.slow();

    const seededData = await seedLoadMoreData();

    try {
      await loadHomePage(page);

      const productCards = getHomeProductCards(page);
      const expectedInitialProducts = seededData.products.slice(0, 6);
      const expectedPageTwoProducts = seededData.products.slice(6);

      await expect(productCards).toHaveCount(expectedInitialProducts.length, {
        timeout: 10000,
      });

      for (const product of expectedInitialProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }

      await expect(getLoadMoreButton(page)).toBeVisible();

      const loadMoreResponsePromise = waitForProductListResponse(page, 2);
      await getLoadMoreButton(page).click();
      const loadMoreResponse = await loadMoreResponsePromise;
      expect(loadMoreResponse.ok()).toBeTruthy();

      const responseData = await loadMoreResponse.json();
      const appendedProducts = responseData?.products || [];

      expect(appendedProducts.length).toBeGreaterThanOrEqual(
        expectedPageTwoProducts.length,
      );

      await expect(productCards).toHaveCount(
        expectedInitialProducts.length + appendedProducts.length,
        {
          timeout: 10000,
        },
      );

      for (const product of expectedPageTwoProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }
    } finally {
      await cleanupSeededLoadMoreData({
        categoryId: seededData.category._id,
        productIds: seededData.products.map((product) => product._id),
      });
    }
  });

  test("keeps category and price filters while loading more filtered products", async ({
    page,
  }) => {
    test.slow();

    const seededData = await seedLoadMoreData();

    try {
      await loadHomePage(page);

      const expectedFilteredPageOneProducts = seededData.products.slice(0, 6);
      const expectedFilteredPageTwoProducts = seededData.products.slice(6);

      const categoryResponsePromise = waitForFilterResponse(page);
      await getCategoryOptions(page).getByText(seededData.category.name).click();
      const categoryResponse = await categoryResponsePromise;
      expect(categoryResponse.ok()).toBeTruthy();

      const priceResponsePromise = waitForFilterResponse(page);
      await getPriceOptions(page).getByText("$20 to 39").click();
      const priceResponse = await priceResponsePromise;
      expect(priceResponse.ok()).toBeTruthy();

      const productCards = getHomeProductCards(page);
      await expect(productCards).toHaveCount(
        expectedFilteredPageOneProducts.length,
        {
          timeout: 10000,
        },
      );

      await expect(getLoadMoreButton(page)).toBeVisible();

      const loadMoreResponsePromise = waitForFilterResponse(page);
      await getLoadMoreButton(page).click();
      const loadMoreResponse = await loadMoreResponsePromise;
      expect(loadMoreResponse.ok()).toBeTruthy();

      const requestPayload = loadMoreResponse.request().postDataJSON();
      expect(requestPayload?.page).toBe(2);
      expect(requestPayload?.checked || []).toEqual([
        seededData.category._id.toString(),
      ]);
      expect(requestPayload?.radio || []).toEqual(seededPriceRange);

      const responseData = await loadMoreResponse.json();
      const appendedProducts = responseData?.products || [];

      expect(appendedProducts.length).toBe(expectedFilteredPageTwoProducts.length);

      await expect(productCards).toHaveCount(
        expectedFilteredPageOneProducts.length + appendedProducts.length,
        { timeout: 10000 },
      );

      for (const product of expectedFilteredPageOneProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }

      for (const product of expectedFilteredPageTwoProducts) {
        await expect(getProductPanel(page)).toContainText(product.name);
      }
    } finally {
      await cleanupSeededLoadMoreData({
        categoryId: seededData.category._id,
        productIds: seededData.products.map((product) => product._id),
      });
    }
  });
});

test.describe("User interface", () => {
  test("shows the banner, product heading, and filter section headings", async ({
    page,
  }) => {
    await loadHomePage(page);

    await expect(page.getByAltText("bannerimage")).toBeVisible();
    await expect(page.locator("h1.text-center")).toContainText("All Products");
    await expect(
      getFilterPanel(page).getByText("Filter By Category"),
    ).toBeVisible();
    await expect(
      getFilterPanel(page).getByText("Filter By Price"),
    ).toBeVisible();
    await expect(
      getFilterPanel(page).getByRole("button", { name: /reset filters/i }),
    ).toBeVisible();
  });

  test("shows category checkboxes and price radio options", async ({
    page,
  }) => {
    await loadHomePage(page);

    await expect(getCategoryOptions(page).first()).toBeVisible();
    await expect(getPriceOptions(page).first()).toBeVisible();
    expect(await getCategoryOptions(page).count()).toBeGreaterThan(0);
    expect(await getPriceOptions(page).count()).toBeGreaterThan(0);
  });

  test("shows product cards with image, name, price, description, and action buttons", async ({
    page,
  }) => {
    await loadHomePage(page);

    const firstCard = getHomeProductCards(page).first();
    await expect(firstCard).toBeVisible();
    await expect(firstCard.locator("img.card-img-top")).toBeVisible();
    await expect(firstCard.locator(".card-title").first()).toBeVisible();
    await expect(firstCard.locator(".card-price")).toContainText("$");
    await expect(firstCard.locator(".card-text")).toBeVisible();
    await expect(
      firstCard.getByRole("button", { name: "More Details" }),
    ).toBeVisible();
    await expect(
      firstCard.getByRole("button", { name: "ADD TO CART" }),
    ).toBeVisible();
  });

  test("shows the header cart link and cart badge on the homepage", async ({
    page,
  }) => {
    await loadHomePage(page);

    await expect(page.locator("a[href='/cart']")).toBeVisible();
    await expect(getCartBadge(page)).toBeVisible();
    await expect(getCartBadge(page)).toHaveAttribute("title", "0");
  });
});
