// Teo Kai Xiang, A20272558U
// Test cases generated by GPT-5.3-Codex via planning mode. Reviewed and edited by me afterwards

import categoryModel from "./categoryModel.js";

describe("categoryModel", () => {
  describe("Happy Path Tests - when everything works as expected, the model", () => {
    test("should be registered with model name Category", () => {
      // Arrange & Act
      const modelName = categoryModel.modelName;

      // Assert
      expect(modelName).toBe("Category");
    });

    test("should define name and slug fields as String", () => {
      // Arrange & Act
      const schemaPaths = categoryModel.schema.paths;

      // Assert
      expect(schemaPaths.name).toBeDefined();
      expect(schemaPaths.name.instance).toBe("String");
      expect(schemaPaths.slug).toBeDefined();
      expect(schemaPaths.slug.instance).toBe("String");
    });

    test("should lowercase slug value via schema option", () => {
      // Arrange
      const category = new categoryModel({
        name: "Electronics",
        slug: "My-SLUG",
      });

      // Act
      const { slug } = category;

      // Assert
      expect(slug).toBe("my-slug");
    });

    test("should allow validation when only name is provided", () => {
      // Arrange
      const category = new categoryModel({ name: "Books" });

      // Act
      const err = category.validateSync();

      // Assert
      expect(err).toBeUndefined();
    });
  });

  describe("Unhappy Path Tests - when there are issues, the model", () => {
    test("should allow missing name because name is not required", () => {
      // Arrange
      const category = new categoryModel({ slug: "no-name" });

      // Act
      const err = category.validateSync();

      // Assert
      expect(err).toBeUndefined();
      expect(category.name).toBeUndefined();
    });

    test("should cast non-string name values to String", () => {
      // Arrange
      const category = new categoryModel({ name: 12345, slug: "numbers" });

      // Act
      const { name } = category;
      const err = category.validateSync();

      // Assert
      expect(name).toBe("12345");
      expect(err).toBeUndefined();
    });
  });
});
